# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/approver.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/approver.proto\x12\x08\x61pprover\x1a\x1egoogle/protobuf/wrappers.proto\"6\n\x08\x41pprover\x12*\n\x06status\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\"!\n\x12GetApproverRequest\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\x05\";\n\x13GetApproverResponse\x12$\n\x08\x61pprover\x18\x01 \x01(\x0b\x32\x12.approver.Approver2]\n\x0f\x41pproverService\x12J\n\x0bGetApprover\x12\x1c.approver.GetApproverRequest\x1a\x1d.approver.GetApproverResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.approver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APPROVER']._serialized_start=67
  _globals['_APPROVER']._serialized_end=121
  _globals['_GETAPPROVERREQUEST']._serialized_start=123
  _globals['_GETAPPROVERREQUEST']._serialized_end=156
  _globals['_GETAPPROVERRESPONSE']._serialized_start=158
  _globals['_GETAPPROVERRESPONSE']._serialized_end=217
  _globals['_APPROVERSERVICE']._serialized_start=219
  _globals['_APPROVERSERVICE']._serialized_end=312
# @@protoc_insertion_point(module_scope)
