# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import todo_pb2 as protos_dot_todo__pb2


class TodoServiceStub(object):
    """Создаем сервис

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTodo = channel.unary_unary(
                '/todo.TodoService/CreateTodo',
                request_serializer=protos_dot_todo__pb2.CreateTodoRequest.SerializeToString,
                response_deserializer=protos_dot_todo__pb2.CreateTodoResponse.FromString,
                )
        self.ListTodos = channel.unary_unary(
                '/todo.TodoService/ListTodos',
                request_serializer=protos_dot_todo__pb2.ListTodosRequest.SerializeToString,
                response_deserializer=protos_dot_todo__pb2.ListTodosResponse.FromString,
                )
        self.GetTodoId = channel.unary_unary(
                '/todo.TodoService/GetTodoId',
                request_serializer=protos_dot_todo__pb2.GetTodoIdRequest.SerializeToString,
                response_deserializer=protos_dot_todo__pb2.GetTodoIdResponse.FromString,
                )
        self.UpdateTodoId = channel.unary_unary(
                '/todo.TodoService/UpdateTodoId',
                request_serializer=protos_dot_todo__pb2.UpdateTodoIdRequest.SerializeToString,
                response_deserializer=protos_dot_todo__pb2.UpdateTodoIdResponse.FromString,
                )
        self.DeleteTodoId = channel.unary_unary(
                '/todo.TodoService/DeleteTodoId',
                request_serializer=protos_dot_todo__pb2.DeleteTodoRequest.SerializeToString,
                response_deserializer=protos_dot_todo__pb2.DeleteTodoResponse.FromString,
                )
        self.GetTodoApprover = channel.unary_unary(
                '/todo.TodoService/GetTodoApprover',
                request_serializer=protos_dot_todo__pb2.GetTodoIdRequest.SerializeToString,
                response_deserializer=protos_dot_todo__pb2.GetTodoApproverResponse.FromString,
                )


class TodoServiceServicer(object):
    """Создаем сервис

    """

    def CreateTodo(self, request, context):
        """Создаем метод, который надо будет реализовать
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTodos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTodoId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTodoId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTodoId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTodoApprover(self, request, context):
        """approver service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TodoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTodo,
                    request_deserializer=protos_dot_todo__pb2.CreateTodoRequest.FromString,
                    response_serializer=protos_dot_todo__pb2.CreateTodoResponse.SerializeToString,
            ),
            'ListTodos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTodos,
                    request_deserializer=protos_dot_todo__pb2.ListTodosRequest.FromString,
                    response_serializer=protos_dot_todo__pb2.ListTodosResponse.SerializeToString,
            ),
            'GetTodoId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTodoId,
                    request_deserializer=protos_dot_todo__pb2.GetTodoIdRequest.FromString,
                    response_serializer=protos_dot_todo__pb2.GetTodoIdResponse.SerializeToString,
            ),
            'UpdateTodoId': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTodoId,
                    request_deserializer=protos_dot_todo__pb2.UpdateTodoIdRequest.FromString,
                    response_serializer=protos_dot_todo__pb2.UpdateTodoIdResponse.SerializeToString,
            ),
            'DeleteTodoId': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTodoId,
                    request_deserializer=protos_dot_todo__pb2.DeleteTodoRequest.FromString,
                    response_serializer=protos_dot_todo__pb2.DeleteTodoResponse.SerializeToString,
            ),
            'GetTodoApprover': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTodoApprover,
                    request_deserializer=protos_dot_todo__pb2.GetTodoIdRequest.FromString,
                    response_serializer=protos_dot_todo__pb2.GetTodoApproverResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'todo.TodoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TodoService(object):
    """Создаем сервис

    """

    @staticmethod
    def CreateTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todo.TodoService/CreateTodo',
            protos_dot_todo__pb2.CreateTodoRequest.SerializeToString,
            protos_dot_todo__pb2.CreateTodoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTodos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todo.TodoService/ListTodos',
            protos_dot_todo__pb2.ListTodosRequest.SerializeToString,
            protos_dot_todo__pb2.ListTodosResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTodoId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todo.TodoService/GetTodoId',
            protos_dot_todo__pb2.GetTodoIdRequest.SerializeToString,
            protos_dot_todo__pb2.GetTodoIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTodoId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todo.TodoService/UpdateTodoId',
            protos_dot_todo__pb2.UpdateTodoIdRequest.SerializeToString,
            protos_dot_todo__pb2.UpdateTodoIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTodoId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todo.TodoService/DeleteTodoId',
            protos_dot_todo__pb2.DeleteTodoRequest.SerializeToString,
            protos_dot_todo__pb2.DeleteTodoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTodoApprover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todo.TodoService/GetTodoApprover',
            protos_dot_todo__pb2.GetTodoIdRequest.SerializeToString,
            protos_dot_todo__pb2.GetTodoApproverResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
